name: Upload S3

# Only trigger, when the nightly benchmark workflow succeeded
on:
  workflow_run:
    workflows: ["Nightly Benchmarks"]
    types:
      - completed

jobs:
  cases:
    name: ${{ matrix.os }}, python${{ matrix.python-version }}, ${{ matrix.case-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        case-name: [defaults]
      
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: nihgtly_benchmarks.yml
          workflow_conclusion: success
          name: nightly_benchmarks
          path: ./benchmarks/

      - name: upload to s3
        run: |
          aws s3 sync ./benchmarks s3://qutip-benchmark-data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.QUTIP_BENCHMARK_S3_KEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.QUTIP_BENCHMARK_S3_SECRET }}
          AWS_EC2_METADATA_DISABLED: true
